apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-app
  template:
    metadata:
      labels:
        app: music-app
    spec:
      containers:
        - name: music-app-container
          image: ibrahimkhalilullah21/music-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: music-app-service
  namespace: production
spec:
  selector:
    app: music-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
